POST http://localhost:3000/v1/province/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNWZiN2VmOTBlYTViMWYxNjM0ZmU3MDQzIiwidG9rZW5faWQiOiI1ZmI3ZWZkMmVhNWIxZjE2MzRmZTcwNDUiLCJpYXQiOjE2MDU4OTAwMDJ9.LydyRZdPrX-knkQOcb-XxyVBgjgU7xCH9CZggMBNlS4

{
    "name": "Buenos Aires",
    "enabled": true
}

###
GET http://localhost:3000/v1/profile/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNWZiMmU1MTAyNWJiYzYxZmZhNzcwOGM1IiwidG9rZW5faWQiOiI1ZmIyZTg5MzI1YmJjNjFmZmE3NzA4ZDciLCJpYXQiOjE2MDU1NjA0Njd9.iww18_ceR8YOByjMmGhIZjgBpUanRaeoGLp0DP0_Q_E
###

GET localhost:3000/v1/image/bfb73330-2b4e-11eb-86ba-3724b418dd5b
### 
GET http://localhost:3000/v1/profile/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNWZiN2YwZTBlYTViMWYxNjM0ZmU3MDRhIiwidG9rZW5faWQiOiI1ZmMwNzE3ODY5ZDc4MDMxZDgxYmI2Y2YiLCJpYXQiOjE2MDY0NDc0ODB9.uNmdQyFLYhtLNr08CkKXyI0IdSpeeX-2dpA27K0FFhc

### 
GET http://localhost:3000/v1/profile/avatar
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNWZiN2YwZTBlYTViMWYxNjM0ZmU3MDRhIiwidG9rZW5faWQiOiI1ZmMwNzE3ODY5ZDc4MDMxZDgxYmI2Y2YiLCJpYXQiOjE2MDY0NDc0ODB9.uNmdQyFLYhtLNr08CkKXyI0IdSpeeX-2dpA27K0FFhc

###
GET http://localhost:3000/v1/pet/5fb7f123ea5b1f1634fe704e
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNWZiN2YwZTBlYTViMWYxNjM0ZmU3MDRhIiwidG9rZW5faWQiOiI1ZmMwNzE3ODY5ZDc4MDMxZDgxYmI2Y2YiLCJpYXQiOjE2MDY0NDc0ODB9.uNmdQyFLYhtLNr08CkKXyI0IdSpeeX-2dpA27K0FFhc

###

GET http://localhost:3000/v1/posts
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNWZiN2YwZTBlYTViMWYxNjM0ZmU3MDRhIiwidG9rZW5faWQiOiI1ZmMwNzE3ODY5ZDc4MDMxZDgxYmI2Y2YiLCJpYXQiOjE2MDY0NDc0ODB9.uNmdQyFLYhtLNr08CkKXyI0IdSpeeX-2dpA27K0FFhc

###
GET http://localhost:3000/v1/pet
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNWZiN2YwZTBlYTViMWYxNjM0ZmU3MDRhIiwidG9rZW5faWQiOiI1ZmMwNzE3ODY5ZDc4MDMxZDgxYmI2Y2YiLCJpYXQiOjE2MDY0NDc0ODB9.uNmdQyFLYhtLNr08CkKXyI0IdSpeeX-2dpA27K0FFhc

###
GET http://localhost:3000/v1/posts/5fc3f6902da2192a30fb9266
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNWZiN2YwZTBlYTViMWYxNjM0ZmU3MDRhIiwidG9rZW5faWQiOiI1ZmMwNzE3ODY5ZDc4MDMxZDgxYmI2Y2YiLCJpYXQiOjE2MDY0NDc0ODB9.uNmdQyFLYhtLNr08CkKXyI0IdSpeeX-2dpA27K0FFhc
###

GET http://localhost:3000/v1/posts/?page=1&limit=5&timestamp=1606691750321
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNWZiN2YwZTBlYTViMWYxNjM0ZmU3MDRhIiwidG9rZW5faWQiOiI1ZmMwNzE3ODY5ZDc4MDMxZDgxYmI2Y2YiLCJpYXQiOjE2MDY0NDc0ODB9.uNmdQyFLYhtLNr08CkKXyI0IdSpeeX-2dpA27K0FFhc

###
GET http://localhost:3000/v1/posts/?page=5&limit=4&timestamp=1606694992010
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNWZiN2YwZTBlYTViMWYxNjM0ZmU3MDRhIiwidG9rZW5faWQiOiI1ZmMwNzE3ODY5ZDc4MDMxZDgxYmI2Y2YiLCJpYXQiOjE2MDY0NDc0ODB9.uNmdQyFLYhtLNr08CkKXyI0IdSpeeX-2dpA27K0FFhc
 